### PR TITLE
Matomo paella 7 plugin

### PR DESCRIPTION
**Pull request by mliradelc**
Hi @ferserc1 and @miesgre 

After almost threw away my table like the old ASCII memes (ノಠ益ಠ)ノ彡┻━┻, I eased my mind and I restarted to work with Paella for the plugin.

Last time @ferserc1 made a Tutorial that I followed, and thanks to that tutorial I solved the context problem that I had. With the code snipped shared to me, I was able to load Matomo JavaScript library necessary for the plugin.

Now I have a little problem, If I run the code directly works perfectly, but when I try to build with Opencast, ESLint throws the error that it can’t find the `Matomo` variable. I tried to add it as a variable, object, etc. But that wrecks the code.

```
[INFO] --- frontend-maven-plugin:1.10.3:npm (check) @ opencast-engage-paella-player-7 ---
[INFO] Running 'npm run check' in /home/runner/work/opencast/opencast/modules/engage-paella-player-7
[INFO] 
[INFO] > check
[INFO] > npm run eslint && npm run html-linter && npm run html-validate
[INFO] 
[INFO] 
[INFO] > eslint
[INFO] > eslint --config .eslintrc.js src --resolve-plugins-relative-to .
[INFO] 
[INFO] 
[INFO] /home/runner/work/opencast/opencast/modules/engage-paella-player-7/src/plugins/org.opencast.paella.opencast.matomoTrackingDataPlugin.js
[INFO]   66:33  error  'Matomo' is not defined  no-undef
[INFO]   67:62  error  'Matomo' is not defined  no-undef
[INFO] 
[INFO] ✖ 2 problems (2 errors, 0 warnings)
```

Do you have any idea on how to overcome with this issue?

### CODE REVIEW

**Comment by mliradelc** [comment]
PS: Can you rebase to develop the paella 7 branch?

**Comment by miesgre** [comment]
> Hi @ferserc1 and @miesgre
> 
> After almost threw away my table like the old ASCII memes (ノಠ益ಠ)ノ彡┻━┻, I eased my mind and I restarted to work with Paella for the plugin.
> 
> Last time @ferserc1 made a Tutorial that I followed, and thanks to that tutorial I solved the context problem that I had. With the code snipped shared to me, I was able to load Matomo JavaScript library necessary for the plugin.
> 
> Now I have a little problem, If I run the code directly works perfectly, but when I try to build with Opencast, ESLint throws the error that it can’t find the `Matomo` variable. I tried to add it as a variable, object, etc. But that wrecks the code.
> 
> Do you have any idea on how to overcome with this issue?

Hi @mliradelc. I'm going to decline this PR to merge in `polimediaupv/update-paella-7`. This branch in for update the paella player 7 libraries and exists a PR to merge to opencast (https://github.com/opencast/opencast/pull/3751).

As paella 7 is now merged to opencast, I think the best way to integrate your changes is to make the PR directly to opencast (develop branch).

About your issue, I think you need to add Matomo to the eslint globals section (https://github.com/mliradelc/opencast/blob/matomo-paella-7-plugin/modules/engage-paella-player-7/.eslintrc.js#L10)
or add a comment, see https://eslint.org/docs/2.0.0/user-guide/configuring#specifying-globals

**Comment by mliradelc** [comment]
Understood, I will do that.
So all opencast plugins for paella should be directly push into opencast, right?

Later I want to do the standalone version of this plugin, where would be the best place to make the PR?

**Comment by miesgre** [comment]
Yes, opencast plugins should go to the opencast repository and be maintained there.

If you want to make a new standalone plugin for your institution, for example, you can make a new git repository in the same way as [paella-basic-plugins](https://github.com/polimediaupv/paella-basic-plugins).

Then web building your player, you will need to add your new package to the dependencies in the same way the reference player [does](https://github.com/polimediaupv/paella-player/blob/main/package.json#L34-L40).

**Pull request closed without merging**
